"""
drop_digikam_tags.py — Remove autotag-generated tags from the DigiKam SQLite
database while preserving all face/people tags and any manually-created tags.

How it works
────────────
1.  Opens the DigiKam core database (digikam4.db).
2.  Walks the Tags tree and identifies every tag that matches the prefixes /
    bare names produced by autotag.py (country/, scene/, ai:tagged, …).
3.  Skips any tag whose ancestor chain passes through a "People" node (the
    top-level tag DigiKam uses for face recognition).
4.  In a single transaction: deletes matching rows from ImageTags, then deletes
    the tag definitions themselves from Tags (children first).
"""

import logging
import shutil
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

from photo_tools.constants import ALL_PREFIXES, BARE_TAGS, CATEGORY_NAMES

log = logging.getLogger("drop_digikam_tags")


def is_our_tag_name(name: str) -> bool:
    """Return True if *name* (a single DigiKam tag node name) is one we own."""
    low = name.lower()
    return low in BARE_TAGS or low in CATEGORY_NAMES


def build_tag_tree(cur: sqlite3.Cursor) -> dict:
    """Return {id: {id, pid, name, children: [id, ...]}} for every tag."""
    cur.execute("SELECT id, pid, name FROM Tags")
    nodes: dict[int, dict] = {}
    for row in cur.fetchall():
        tid, pid, name = row
        nodes[tid] = {"id": tid, "pid": pid, "name": name, "children": []}
    for tid, node in nodes.items():
        parent = nodes.get(node["pid"])
        if parent:
            parent["children"].append(tid)
    return nodes


def find_people_ids(nodes: dict) -> set[int]:
    """Return the IDs of all tags under the 'People' hierarchy (inclusive)."""
    people_roots = [
        tid for tid, n in nodes.items()
        if n["name"].lower() == "people"
    ]
    result: set[int] = set()

    def _walk(tid: int) -> None:
        result.add(tid)
        for child in nodes[tid]["children"]:
            _walk(child)

    for root in people_roots:
        _walk(root)
    return result


def tag_full_path(nodes: dict, tid: int) -> str:
    """Build the full hierarchical path for a tag, e.g. 'scene/outdoor'."""
    parts: list[str] = []
    cur = tid
    while cur in nodes and nodes[cur]["pid"] != 0:
        parts.append(nodes[cur]["name"])
        cur = nodes[cur]["pid"]
    if cur in nodes:
        parts.append(nodes[cur]["name"])
    parts.reverse()
    return "/".join(parts)


def collect_our_tags(nodes: dict, people_ids: set[int]) -> set[int]:
    """
    Walk the tag tree and collect IDs of tags generated by autotag.py.

    Strategy — a tag is "ours" if:
      • It is NOT in the People hierarchy, AND
      • Its full hierarchical path matches (starts with one of ALL_PREFIXES,
        or is a BARE_TAG),
      OR
      • It is a bare category node that has NO remaining children
        after its autotag children are removed.
    """
    ours: set[int] = set()

    # Pass 1: tag nodes whose full path matches autotag patterns
    for tid, node in nodes.items():
        if tid in people_ids:
            continue
        full = tag_full_path(nodes, tid)
        low = full.lower()
        if low in BARE_TAGS:
            ours.add(tid)
            continue
        for prefix in ALL_PREFIXES:
            if low.startswith(prefix) or low == prefix.rstrip("/"):
                ours.add(tid)
                break

    # Pass 2: collect category parent nodes that are now empty.
    changed = True
    while changed:
        changed = False
        for tid, node in nodes.items():
            if tid in ours or tid in people_ids:
                continue
            name_low = node["name"].lower()
            if name_low not in CATEGORY_NAMES:
                continue
            remaining = [c for c in node["children"] if c not in ours]
            if not remaining:
                ours.add(tid)
                changed = True

    return ours


def run_drop_digikam_tags(args) -> None:
    """Execute the drop-digikam-tags subcommand."""
    db_path: Path = args.database.expanduser().resolve()
    if not db_path.exists():
        print(f"Error: database not found: {db_path}", file=sys.stderr)
        sys.exit(1)

    if args.execute:
        backup = db_path.with_suffix(
            f".bak-{datetime.now():%Y%m%dT%H%M%S}"
        )
        shutil.copy2(db_path, backup)
        print(f"Backup: {backup}")

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='Tags'"
    )
    if not cur.fetchone():
        print("Error: no 'Tags' table — is this a DigiKam database?",
              file=sys.stderr)
        sys.exit(1)

    nodes = build_tag_tree(cur)
    people_ids = find_people_ids(nodes)
    our_ids = collect_our_tags(nodes, people_ids)

    if not our_ids:
        print("Nothing to remove — no autotag-generated tags found.")
        conn.close()
        return

    placeholders = ",".join("?" * len(our_ids))
    cur.execute(
        f"SELECT COUNT(*) FROM ImageTags WHERE tagid IN ({placeholders})",
        list(our_ids),
    )
    assoc_count = cur.fetchone()[0]

    print(f"\nPeople tags (preserved): {len(people_ids)}")
    print(f"Autotag tags to remove:  {len(our_ids)}")
    print(f"Image-tag links to remove: {assoc_count}")

    if log.isEnabledFor(logging.DEBUG):
        print("\nTags to remove:")
        for tid in sorted(our_ids):
            path = tag_full_path(nodes, tid)
            print(f"  [{tid}] {path}")
        if people_ids:
            print("\nPeople tags (kept):")
            for tid in sorted(people_ids):
                path = tag_full_path(nodes, tid)
                print(f"  [{tid}] {path}")

    if not args.execute:
        print("\n** DRY RUN — pass --execute to delete **")
        conn.close()
        return

    cur.execute("BEGIN")
    try:
        cur.execute(
            f"DELETE FROM ImageTags WHERE tagid IN ({placeholders})",
            list(our_ids),
        )
        deleted_assocs = cur.rowcount

        cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='TagsTree'"
        )
        if cur.fetchone():
            cur.execute(
                f"DELETE FROM TagsTree WHERE id IN ({placeholders})",
                list(our_ids),
            )

        depth_order = sorted(
            our_ids,
            key=lambda t: tag_full_path(nodes, t).count("/"),
            reverse=True,
        )
        for tid in depth_order:
            cur.execute("DELETE FROM Tags WHERE id = ?", (tid,))

        conn.commit()
        print(f"\nDone — removed {len(our_ids)} tags and {deleted_assocs} image-tag links.")
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_drop_digikam_tags_parser(subparsers) -> None:
    """Register the 'drop-digikam-tags' subcommand."""
    sub = subparsers.add_parser(
        "drop-digikam-tags",
        help="Remove autotag-generated tags from a DigiKam database.",
    )
    sub.add_argument("database", type=Path, help="Path to digikam4.db")
    sub.add_argument(
        "--execute", action="store_true",
        help="Actually delete (default is dry-run)",
    )
    sub.set_defaults(func=run_drop_digikam_tags)
