"""Shared helpers for photo-tools.

Exiftool operations, file discovery, image preparation, and embedding cache.
Extracted from autotag.py to be shared by duplicates.py and other modules.
"""

import base64
import json
import logging
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from photo_tools.config import get_config
from photo_tools.constants import (
    ALL_PREFIXES,
    BARE_TAGS,
    SUPPORTED_EXTENSIONS,
    VIDEO_EXTENSIONS,
)

log = logging.getLogger("helpers")


# ---------------------------------------------------------------------------
# Tag utilities
# ---------------------------------------------------------------------------

def hierarchical_subject(tag: str) -> str:
    """Convert 'animal/beagle' to 'animal|beagle' for XMP-lr:HierarchicalSubject."""
    return tag.replace("/", "|")


def is_our_tag(tag: str) -> bool:
    """Check if a tag was generated by this tool (has our prefix or is a bare flag)."""
    t = tag.lower()
    if t in BARE_TAGS:
        return True
    for prefix in ALL_PREFIXES:
        if t.startswith(prefix):
            return True
    return False


def deduplicate(tags: list[str]) -> list[str]:
    seen = set()
    deduped = []
    for t in tags:
        if t and t not in seen:
            seen.add(t)
            deduped.append(t)
    return deduped


# ---------------------------------------------------------------------------
# Exiftool tag operations (unified — replaces 5 copy-pasted patterns)
# ---------------------------------------------------------------------------

_TAG_FIELDS = (
    "IPTC:Keywords",
    "XMP-dc:Subject",
    "XMP-lr:HierarchicalSubject",
    "XMP-digiKam:TagsList",
)


def _build_tag_args(tag: str, operator: str) -> list[str]:
    """Build exiftool args for a single tag. operator is '+=' or '-='."""
    hs = hierarchical_subject(tag)
    return [
        f"-IPTC:Keywords{operator}{tag}",
        f"-XMP-dc:Subject{operator}{tag}",
        f"-XMP-lr:HierarchicalSubject{operator}{hs}",
        f"-XMP-digiKam:TagsList{operator}{tag}",
    ]


def add_tags(path: Path, keywords: list[str], dry_run: bool = False) -> bool:
    """Add tags to a single file using exiftool."""
    if not keywords:
        log.warning("No keywords to write for %s", path.name)
        return False
    if dry_run:
        log.info("[DRY RUN] Would write %d keywords to %s:", len(keywords), path.name)
        for kw in sorted(keywords):
            log.info("    %s", kw)
        return True

    args = ["exiftool", "-overwrite_original"]
    for kw in keywords:
        args.extend(_build_tag_args(kw, "+="))
    args.append(str(path))

    cfg = get_config()
    try:
        result = subprocess.run(args, capture_output=True, text=True,
                                timeout=cfg.exiftool.timeout)
        if result.returncode != 0:
            log.error("exiftool failed for %s: %s", path.name, result.stderr.strip())
            return False
        log.info("Wrote %d keywords to %s", len(keywords), path.name)
        return True
    except FileNotFoundError:
        log.error("exiftool not found. Install with: brew install exiftool")
        sys.exit(1)
    except Exception as e:
        log.error("Failed to write keywords to %s: %s", path.name, e)
        return False


def remove_tags(
    paths: list[Path],
    tags: list[str],
    *,
    also_remove_leaves: bool = False,
    dry_run: bool = False,
) -> bool:
    """Remove tags from one or more files using exiftool.

    Unifies clear_our_tags (autotag), apply_tag_change and bulk_delete_tags (duplicates).
    """
    if not paths or not tags:
        return True
    if dry_run:
        log.info("[DRY RUN] Would remove %d tag(s) from %d file(s)", len(tags), len(paths))
        return True

    cfg = get_config()
    batch_size = cfg.exiftool.batch_size
    success = True

    for i in range(0, len(paths), batch_size):
        batch = paths[i:i + batch_size]
        args = ["exiftool", "-overwrite_original"]
        for tag in tags:
            args.extend(_build_tag_args(tag, "-="))
            if also_remove_leaves:
                leaf = tag.rsplit("/", 1)[-1]
                if leaf != tag:
                    args.append(f"-IPTC:Keywords-={leaf}")
                    args.append(f"-XMP-dc:Subject-={leaf}")
        args.extend(str(f) for f in batch)

        try:
            result = subprocess.run(args, capture_output=True, text=True,
                                    timeout=cfg.exiftool.timeout)
            if result.returncode != 0:
                log.warning("Could not remove tags: %s", result.stderr.strip())
                success = False
        except Exception as e:
            log.warning("Error removing tags: %s", e)
            success = False

    return success


def clear_all_keywords(path: Path, dry_run: bool = False) -> bool:
    """Nuclear option: remove ALL IPTC keywords and XMP subjects from a file."""
    if dry_run:
        log.info("[DRY RUN] Would clear ALL keywords from %s", path.name)
        return True

    args = [
        "exiftool", "-overwrite_original",
        "-IPTC:Keywords=", "-XMP-dc:Subject=",
        "-XMP-lr:HierarchicalSubject=", "-XMP-digiKam:TagsList=",
        str(path),
    ]
    cfg = get_config()
    try:
        result = subprocess.run(args, capture_output=True, text=True,
                                timeout=cfg.exiftool.timeout)
        if result.returncode != 0:
            log.warning("Could not clear keywords from %s: %s", path.name, result.stderr.strip())
            return False
        log.debug("Cleared ALL keywords from %s", path.name)
        return True
    except Exception as e:
        log.warning("Error clearing keywords from %s: %s", path.name, e)
        return False


# ---------------------------------------------------------------------------
# EXIF reading
# ---------------------------------------------------------------------------

def read_exif(path: Path) -> dict:
    fields = [
        "-j",
        "-GPS:GPSLatitude", "-GPS:GPSLongitude",
        "-GPS:GPSLatitudeRef", "-GPS:GPSLongitudeRef",
        "-EXIF:Make", "-EXIF:Model",
        "-EXIF:DateTimeOriginal", "-EXIF:CreateDate",
        "-EXIF:Flash",
        "-EXIF:ImageWidth", "-EXIF:ImageHeight",
        "-File:ImageWidth", "-File:ImageHeight",
        "-IPTC:Keywords", "-XMP:Subject", "-XMP-digiKam:TagsList",
        "-n",
    ]
    try:
        result = subprocess.run(
            ["exiftool"] + fields + [str(path)],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            return {}
        meta = json.loads(result.stdout)
        return meta[0] if meta else {}
    except Exception as e:
        log.warning("Could not read EXIF from %s: %s", path, e)
        return {}


def get_existing_keywords(exif: dict) -> set[str]:
    keywords = set()
    for field in ("Keywords", "Subject", "TagsList"):
        val = exif.get(field, [])
        if isinstance(val, str):
            keywords.add(val.lower())
        elif isinstance(val, list):
            keywords.update(str(v).lower() for v in val)
    # Drop flat tags that are just the leaf of a hierarchical tag already present
    leaves = {t.rsplit("/", 1)[-1] for t in keywords if "/" in t}
    return {t for t in keywords if "/" in t or t not in leaves}


def read_keywords_batch(paths: list[Path]) -> dict[Path, set[str]]:
    """Read IPTC:Keywords + XMP:Subject from all paths in batched exiftool calls."""
    if not paths:
        return {}

    cfg = get_config()
    batch_size = cfg.exiftool.batch_size
    result: dict[Path, set[str]] = {}

    for i in range(0, len(paths), batch_size):
        batch = paths[i:i + batch_size]
        try:
            proc = subprocess.run(
                ["exiftool", "-j", "-IPTC:Keywords", "-XMP:Subject", "-XMP-digiKam:TagsList"]
                + [str(p) for p in batch],
                capture_output=True, text=True, timeout=120,
            )
            if proc.returncode != 0:
                for p in batch:
                    exif = read_exif(p)
                    result[p] = get_existing_keywords(exif)
                continue
            meta_list = json.loads(proc.stdout)
        except Exception:
            for p in batch:
                exif = read_exif(p)
                result[p] = get_existing_keywords(exif)
            continue

        str_to_path = {str(p): p for p in batch}
        for meta in meta_list:
            source = meta.get("SourceFile", "")
            path = str_to_path.get(source, Path(source))
            result[path] = get_existing_keywords(meta)

    return result


# ---------------------------------------------------------------------------
# Image preparation (convert + downsize)
# ---------------------------------------------------------------------------

try:
    import pillow_heif
    pillow_heif.register_heif_opener()
    _HAVE_PILLOW_HEIF = True
except ImportError:
    _HAVE_PILLOW_HEIF = False

try:
    from PIL import Image as PILImage, ImageOps
    _HAVE_PILLOW = True
except ImportError:
    _HAVE_PILLOW = False


def _try_pillow(path: Path, tmp_path: str, max_pixels: int) -> bool:
    if not _HAVE_PILLOW:
        return False
    if path.suffix.lower() in (".heic", ".heif") and not _HAVE_PILLOW_HEIF:
        return False
    try:
        cfg = get_config()
        img = PILImage.open(str(path))
        ImageOps.exif_transpose(img, in_place=True)
        img.thumbnail((max_pixels, max_pixels), PILImage.LANCZOS)
        if img.mode not in ("RGB", "L"):
            img = img.convert("RGB")
        img.save(tmp_path, "JPEG", quality=cfg.image.jpeg_quality)
        return Path(tmp_path).stat().st_size > 0
    except Exception:
        return False


def _try_ffmpeg(path: Path, tmp_path: str, max_pixels: int) -> bool:
    scale_filter = (
        f"scale='if(gt(iw,ih),{max_pixels},-2)':'if(gt(iw,ih),-2,{max_pixels})'"
    )
    try:
        result = subprocess.run(
            ["ffmpeg", "-y", "-i", str(path), "-frames:v", "1",
             "-vf", scale_filter, "-q:v", "2", tmp_path],
            capture_output=True, text=True, timeout=30,
        )
        return result.returncode == 0 and Path(tmp_path).stat().st_size > 0
    except Exception:
        return False


def _try_magick(path: Path, tmp_path: str, max_pixels: int) -> bool:
    cfg = get_config()
    for cmd in ["magick", "convert"]:
        try:
            result = subprocess.run(
                [cmd, str(path), "-resize", f"{max_pixels}x{max_pixels}>",
                 "-quality", str(cfg.image.jpeg_quality), tmp_path],
                capture_output=True, text=True, timeout=30,
            )
            if result.returncode == 0 and Path(tmp_path).stat().st_size > 0:
                return True
        except Exception:
            continue
    return False


def prepare_image(path: Path, max_pixels: int) -> Path | None:
    """Convert any image to JPEG and downsize to max_pixels on the long edge.
    Returns path to a temp JPEG, or None on failure. Caller must delete the file."""
    tmp = tempfile.NamedTemporaryFile(suffix=".jpg", delete=False)
    tmp.close()
    tmp_path = tmp.name

    try:
        if _try_pillow(path, tmp_path, max_pixels):
            return Path(tmp_path)
        if _try_ffmpeg(path, tmp_path, max_pixels):
            return Path(tmp_path)
        if _try_magick(path, tmp_path, max_pixels):
            return Path(tmp_path)

        log.warning("Could not convert %s — install pillow-heif, ffmpeg, or imagemagick",
                    path.name)
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        return None

    except Exception as e:
        log.warning("prepare_image error for %s: %s", path.name, e)
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        return None


# ---------------------------------------------------------------------------
# File type detection
# ---------------------------------------------------------------------------

def detect_real_type(path: Path) -> str | None:
    """Check actual file type by reading magic bytes. Returns 'image', 'video', or None."""
    try:
        with open(path, "rb") as f:
            header = f.read(12)
    except Exception:
        return None

    if header[:2] == b"\xff\xd8":
        return "image"
    if header[:4] == b"\x89PNG":
        return "image"
    if header[:4] in (b"II\x2a\x00", b"MM\x00\x2a"):
        return "image"
    if header[:4] == b"RIFF" and header[8:12] == b"WEBP":
        return "image"
    if header[4:8] == b"ftyp":
        ftyp = header[8:12].lower()
        if ftyp in (b"heic", b"heix", b"mif1", b"msf1"):
            return "image"
        if ftyp in (b"qt  ", b"mp41", b"mp42", b"isom", b"m4v ", b"msnv", b"avc1"):
            return "video"
    if header[4:8] == b"ftyp":
        return "video"
    if header[:4] == b"RIFF" and header[8:12] == b"AVI ":
        return "video"
    if header[:4] == b"\x1a\x45\xdf\xa3":
        return "video"

    return None


def is_video(path: Path) -> bool:
    """Check if a file is a video, by extension or magic bytes."""
    if path.suffix.lower() in VIDEO_EXTENSIONS:
        return True
    return detect_real_type(path) == "video"


# ---------------------------------------------------------------------------
# Video frame extraction
# ---------------------------------------------------------------------------

def extract_video_frame(path: Path) -> Path | None:
    """Extract a single representative frame from a video using ffmpeg."""
    try:
        tmp = tempfile.NamedTemporaryFile(suffix=".jpg", delete=False)
        tmp.close()

        result = subprocess.run(
            ["ffmpeg", "-y", "-ss", "1", "-i", str(path),
             "-frames:v", "1", "-q:v", "2", tmp.name],
            capture_output=True, text=True, timeout=30,
        )

        if result.returncode != 0:
            result = subprocess.run(
                ["ffmpeg", "-y", "-i", str(path),
                 "-frames:v", "1", "-q:v", "2", tmp.name],
                capture_output=True, text=True, timeout=30,
            )

        if result.returncode != 0 or not Path(tmp.name).exists() or Path(tmp.name).stat().st_size == 0:
            log.warning("ffmpeg could not extract frame from %s", path.name)
            try:
                os.unlink(tmp.name)
            except OSError:
                pass
            return None

        return Path(tmp.name)

    except FileNotFoundError:
        log.warning("ffmpeg not found — skipping video. Install: brew install ffmpeg")
        return None
    except Exception as e:
        log.warning("Frame extraction failed for %s: %s", path.name, e)
        return None


# ---------------------------------------------------------------------------
# CLIP embedding cache (stored in XMP, reused by find-similar)
# ---------------------------------------------------------------------------

_EXIFTOOL_CONFIG = Path(__file__).with_name("exiftool_phototools.config")


def read_clip_cache(path: Path) -> dict:
    result = subprocess.run(
        ["exiftool", "-config", str(_EXIFTOOL_CONFIG), "-j",
         "-XMP-phototools:CLIPEmbedding",
         "-XMP-phototools:CLIPModel",
         "-XMP-phototools:CLIPTimestamp",
         str(path)],
        capture_output=True, text=True, timeout=30,
    )
    if result.returncode != 0:
        return {}
    try:
        meta = json.loads(result.stdout)
    except json.JSONDecodeError:
        return {}
    return meta[0] if meta else {}


def read_cached_embedding(path: Path, model: str) -> np.ndarray | None:
    cache = read_clip_cache(path)
    if cache.get("CLIPModel") != model:
        return None
    b64 = cache.get("CLIPEmbedding", "")
    if not b64:
        return None
    try:
        return np.frombuffer(base64.b64decode(b64), dtype=np.float32).copy()
    except Exception:
        return None


def write_embedding(path: Path, vec: np.ndarray, model: str, dry_run: bool) -> None:
    b64 = base64.b64encode(vec.astype(np.float32).tobytes()).decode()
    ts = datetime.now(timezone.utc).isoformat()
    if dry_run:
        log.info("[DRY RUN] Would cache embedding for %s", path.name)
        return
    cfg = get_config()
    result = subprocess.run(
        ["exiftool", "-config", str(_EXIFTOOL_CONFIG), "-overwrite_original",
         f"-XMP-phototools:CLIPEmbedding={b64}",
         f"-XMP-phototools:CLIPModel={model}",
         f"-XMP-phototools:CLIPTimestamp={ts}",
         str(path)],
        capture_output=True, text=True, timeout=cfg.exiftool.timeout,
    )
    if result.returncode != 0:
        log.warning("Failed to cache embedding for %s: %s",
                    path.name, result.stderr.strip())


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

def find_images(target: Path, recursive: bool = False) -> list[Path]:
    if target.is_file():
        if target.suffix.lower() in SUPPORTED_EXTENSIONS:
            return [target]
        log.warning("Unsupported file type: %s", target)
        return []
    if not target.is_dir():
        log.error("Path does not exist: %s", target)
        return []

    images = []
    pattern = "**/*" if recursive else "*"
    for f in target.glob(pattern):
        if f.is_file() and f.suffix.lower() in SUPPORTED_EXTENSIONS:
            images.append(f)

    seen = set()
    deduped = []
    for img in sorted(images):
        resolved = img.resolve()
        if resolved not in seen:
            seen.add(resolved)
            deduped.append(img)
    return deduped
